### ISSUE TITLE
Merging my list of alfred workflows with this

### ISSUE THREAD

**Issue by nikitavoloboev** [alfred-workflows/awesome-alfred-workflows#47]
I have been curating my own list of [awesome Alfred workflows](https://github.com/learn-anything/alfred-workflows#readme) I personally use and love.

The reason I made it is that I automated fully adding to the list where every change I made to the readme is [automatically committed with Hazel](https://wiki.nikitavoloboev.xyz/macOS/apps/hazel.html). All other lists have really odd practices of one PR per change which creates tons of friction. I also have higher standard of what kind of workflows are accepted as I have tried probably all the publicly released workflows out there.

However I dislike duplicating efforts and I think it would be awesome to have just 1 list out there. As this list is already included in the [awesome](https://github.com/sindresorhus/awesome) repo, I think this list can be that 1 list.

What are your thoughts on this?

**Comment by deanishe** [comment]
> I think it would be awesome to have just 1 list out there

Oh I dunno: "awesome" is a fairly subjective thing. Are the lists mostly duplicates of each other?

Don't you have any technical requirements of your list for integration into your learn-anything system? 

> All other lists have really odd practices of one PR per change which creates tons of friction

It creates friction for the people wanting to submit a whole bunch of stuff, but it makes life easier for everybody else.

**Comment by nikitavoloboev** [comment]
> Are the lists mostly duplicates of each other?

The two lists are essentially duplicates. They just vary in little things that I find valuable. For example having `Contents` be on a `#####` level heading instead of `##` to preserve space. The big difference though is the workflows that are included and the categorization of them. Although which workflows that are included and excluded is highly subjective as 'awesome` means different things to everyone.



> Don't you have any technical requirements of your list for integration into your learn-anything system?

All the [curated lists](https://github.com/learn-anything/curated-lists#readme) under learn-anything organization are nearly identical to awesome lists. The only 'technical' requirement is the structure should be of format:

## Heading
- [Name] - Description.

I am writing a parser that will allow to essentially search and cache both [awesome lists](https://github.com/sindresorhus/awesome) and the [curated lists](https://github.com/learn-anything/curated-lists) to use everything from Alfred without ever having to go to the web interface (GitHub).


> It creates friction for the people wanting to submit a whole bunch of stuff, but it makes life easier for everybody else.

Yeah I agree with you there. The main reason I made the [curated lists](https://github.com/learn-anything/curated-lists) is because I can extend the lists at lightning speed and I found a few of the 'awesome' lists not that 'awesome' (in my opinion). This awesome list including.

My workflow with editing the lists is as simple as running a KM macro with Karabiner that with two keys pressed will open the `readme.md` of the list. For example pressing `1 + w` will run this macro and open the list in Sublime Text:

![2018-06-11 at 19 13](https://user-images.githubusercontent.com/6391776/41246511-96c70ec2-6dab-11e8-908c-54d20e22ced3.png)

I then run this macro to go to the heading I need in this opened file in Sublime:
![2018-06-11 at 19 14](https://user-images.githubusercontent.com/6391776/41246550-b8e94cea-6dab-11e8-9bff-e1cc488b4023.png)

And I make the change. The change than is instantly pushed to GitHub with Hazel. This way I can make a change in under 2 seconds time and not go through the whole PR thing in GitHub, with 1 PR per change.

Also I don't put too much value into commit names in curated lists as going back in history in my experience is never needed so all my commit messages are of type `add alfred workflow` or similar.

All that is to say that I don't mind removing the alfred workflows curated list that I maintain and merge it into this list and adding me as maintainer too. You can take a look at my [current Alfred workflows list](https://github.com/learn-anything/alfred-workflows#readme). Ideally I would like to keep the same format but change the badge from `More Lists` to `Awesome`. 

What do you think?

**Comment by nikitavoloboev** [comment]
Oh and I also [made a badge](https://github.com/learn-anything/alfred-workflows#github-badge) that Alfred Workflows can add to their repo to see more awesome workflows. With Packal essentially being obsolete, workflow discoverability is quite lacking.

**Comment by nikitavoloboev** [comment]
Oh and one other thing I do dislike about awesome lists at current time is that the [main awesome list repo](https://github.com/sindresorhus/awesome#readme) has so much unnecessary stuff. Like Sindre advertising his blog or twitter or the huge banner at the front. 

I think curated lists should have nothing that is not related to content in the lists. The value are the links and the contribution guidelines, nothing else. In my opinion. So in this way I really like the list I currently maintain, it just irks me to have multiple options out there doing essentially the same thing.

**Comment by derimagia** [comment]
Having them as separate commits is pretty important to me, the more people that contribute the more that less useful comes in. A lot of times you'll have people add more than one. 

Seeing as this list isn't contributed to as often I wouldn't mind laxing the rule for now and allowing them to just make a single issue for discussions, but that's just because this isn't touched much. 

I do think that having generic commits is detrimental to a list. Looking down your commits I see "update readme" and "update workflows". I often use this to go back and see what's new in a list. Obviously a git diff could work but it's a lot cleaner and saves headaches as @deanishe said. 

This could be something CI could handle. I.G. the users creates an issue and CI splits them into PRs, or something of the sort. But I don't know exactly how often people avoid adding to the list.

I am up for a certainly link to your repo in the "Other Lists" section. I don't know about the badge yet because it wouldn't really fit in with the others and the text you have is generic for it. I do like the look of it.

I am not against cooperation though. I'm going to take a closer look at your list over the weekend

**Comment by deanishe** [comment]
> I do think that having generic commits is detrimental to a list.

A good commit log has a beauty all of its own. One workflow per PR is definitely the right policy, imo.

> But I don't know exactly how often people avoid adding to the list.

Not too frequently, I suspect. I follow the Alfred community pretty closely, and there just aren't many new workflows (of substance) being made at the moment. We need some new toys, I guess…

As far as barriers to making a submission go, how much of an issue is the single-file format wrt to multiple PRs? I'm crap at merging. Do multiple changes to the same file always need manual merging?

Rather than sit and wait for submissions, how about #48?

**Comment by derimagia** [comment]
I took a better look through the list and there are definitely a lot of workflows which seem really good.

I'd be fine with committing/rebasing directly on master, merges are better with merge conflicts which we aren't going to have many of.. To avoid merges we would just need some type of structured file and then the tool could build the markdown list from it. Merges wouldn't be an issue then. 

For starters @nikitavoloboev if you could only list a few of your most used ones from the list which ones would it be?

**Comment by nikitavoloboev** [comment]
> if you could only list a few of your most used ones from the list which ones would it be?

I mention my most used workflows [here](https://wiki.nikitavoloboev.xyz/macOS/apps/alfred/alfred.html).

**Comment by deanishe** [comment]
> To avoid merges we would just need some type of structured file

You mean something like a single JSON file per workflow, so different PRs are never changing the same files?
